// Real ComfyUI browser integration. Evaluate this function on an isolated QA server.
(async () => {
    const {app}=await import('/scripts/app.js');
    const {api}=await import('/scripts/api.js');
    const check=(ok,msg)=>{if(!ok)throw Error(msg);};
    const widget=(n,name)=>n.widgets.find(w=>w.name===name);
    const set=(n,name,value)=>{const w=widget(n,name);w.value=value;w.callback?.(value);};
    app.graph.clear();
    const create=(id,x,y)=>{const n=LiteGraph.createNode(id);check(n,'Missing '+id);n.pos=[x,y];app.graph.add(n);return n;};
    const crop=create('SwwanCropByMaskV5',20,20);
    const restore=create('SwwanRestoreCropBoxV4',380,20);
    const resize=create('ImageResizeKJv2Alternative',720,20);
    const concat=create('SwwanImageConcatMulti',1060,20);
    const color=create('SwwanColorConverter',20,700);
    const seed=create('SwwanSeed',380,700);
    const math=create('MathExpression_UTK',720,700);
    set(crop,'crop_mode','edit_region');set(crop,'output_size','自定义宽高');set(crop,'custom_width',768);
    check(widget(crop,'detect').hidden,'Crop irrelevant controls visible');
    check(!widget(crop,'custom_width').hidden,'Crop custom width hidden');
    check(crop.outputs.length===6,'Crop output append');
    crop.connect(4,restore,restore.inputs.findIndex(i=>i.name==='region_info'));
    check(!widget(restore,'expand_percent').hidden,'Restore edit params hidden');
    set(resize,'resize_mode','aspect_ratio');set(resize,'aspect_ratio','custom');
    check(!widget(resize,'proportional_width').hidden && widget(resize,'width').hidden,'Aspect controls');
    set(resize,'fill_color','#123456');
    const colorSlot=color.outputs.findIndex(o=>o.type==='COLORCODE');
    check(colorSlot>=0,'COLORCODE output');
    // Built-in widget conversion is intentionally exercised before connecting.
    const {convertToInput}=await import('/extensions/core/widgetInputs.js');
    if (!resize.inputs.some(i=>i.name==='fill_color')) convertToInput(resize,widget(resize,'fill_color'));
    color.connect(colorSlot,resize,resize.inputs.findIndex(i=>i.name==='fill_color'));
    set(concat,'inputcount',4);
    crop.connect(0,concat,concat.inputs.findIndex(i=>i.name==='image_4'));
    set(concat,'inputcount',2);
    check(widget(concat,'inputcount').value===4,'Connected port silently removed');
    check(!seed.widgets.some(w=>w.name==='control_after_generate'),'Conflicting stock seed control');
    seed.properties.swwan_last_seed=40;set(seed,'seed',-2);
    seed.connect(0,math,math.inputs.findIndex(i=>i.name==='a'));set(math,'expression','a');
    const seedId=seed.id, mathId=math.id;
    const before=JSON.parse(JSON.stringify(app.graph.serialize()));
    await app.loadGraphData(before);
    const s=app.graph.getNodeById(seedId),r=app.graph.getNodeById(resize.id),c=app.graph.getNodeById(concat.id);
    check(widget(s,'seed').value===-2 && s.properties.swwan_last_seed===40,'Seed reload');
    check(widget(c,'inputcount').value===4 && c.inputs.find(i=>i.name==='image_4').link!=null,'Dynamic reload');
    check(widget(r,'fill_color').value==='#123456' && r.inputs.find(i=>i.name==='fill_color').link!=null,'Color reload');
    check(widget(app.graph.getNodeById(crop.id),'custom_width').value===768,'Hidden values lost');
    const prompt=await app.graphToPrompt();
    const submitted=await api.queuePrompt(0,prompt);
    check(s.properties.swwan_last_seed===41,'Increment not resolved');
    const history=await new Promise(async (resolve,reject)=>{
        const until=Date.now()+10000;
        while(Date.now()<until){const h=await (await fetch('/history/'+submitted.prompt_id)).json();if(h[submitted.prompt_id]){resolve(h[submitted.prompt_id]);return;}await new Promise(r=>setTimeout(r,100));}reject(Error('History timeout'));
    });
    check(history.status.status_str==='success','CPU seed execution failed');
    check(history.prompt[2][String(seedId)].inputs.seed===41,'Actual seed absent from prompt metadata');
    const wf=history.prompt[3].extra_pnginfo.workflow;
    check(wf.nodes.find(n=>String(n.id)===String(seedId)).widgets_values[0]===41,'Actual seed absent from workflow metadata');
    check(history.outputs[String(mathId)].value[0]===41,'Seed output differs from metadata');
    const {resolveSeed}=await import('/extensions/ComfyUI_Swwan/swwan_seed.js');
    check(resolveSeed(-3,41)===40 && resolveSeed(-1,null,()=>123)===123,'Seed modes');
    s.widgets.find(w=>w.name==='Use last seed').callback();check(widget(s,'seed').value===41,'Use last seed');
    const saved=JSON.parse(JSON.stringify(app.graph.serialize()));
    await app.loadGraphData(saved);
    const loaded=app.graph.getNodeById(seedId);
    check(widget(loaded,'seed').value===41 && loaded.properties.swwan_last_seed===41,'Executed seed save/reload');
    for (const n of [...app.graph._nodes]) if (![String(seedId),String(mathId)].includes(String(n.id))) app.graph.remove(n);
    check(app.graph._nodes.length===2,'Queue graph lost nodes');
    await app.queuePrompt(0,1);
    check(widget(loaded,'seed').value===41,'Fixed seed changed by queue hooks');
    return {passed:true,extensions:app.extensions.map(e=>e.name).filter(n=>n.startsWith('Swwan')),checks:['mode visibility','appended crop outputs','dynamic connected ports','COLORCODE connection/values','seed increment execution/metadata','random/decrement/last','graph save/reload'],workflow:saved};
})
